<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ShellScriptBtn</name>
   <tag></tag>
   <elementGuidId>bdc26dea-5a87-4bcf-b089-9cfb54ad49c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@data-automation-id = 'ShellScript']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7ab50f57-75dd-4a84-a327-d5c6af139078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>ShellScript</value>
      <webElementGuid>bb3fc931-7ab0-43cc-adcc-26caacf981d8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
