<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>close_Btn</name>
   <tag></tag>
   <elementGuidId>eacc49e2-34f4-4f1a-bffb-9646d7e4c250</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'close-manage-profiles']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d738d208-edae-4ce2-8997-98f54f526702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close-manage-profiles</value>
      <webElementGuid>6ac7f966-3590-44f1-a4d9-67b2158c1551</webElementGuid>
   </webElementProperties>
</WebElementEntity>
