<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Notification_JobSubmission</name>
   <tag></tag>
   <elementGuidId>ee0dfa46-8e6b-4644-bd76-b9860e8c17ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[(contains(text(), 'Job has been submitted successfully on') or contains(., 'Job has been submitted successfully on'))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[4]/div/div/div/span[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bc52818b-d743-4731-a405-2373c706cf7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job has been submitted successfully on</value>
      <webElementGuid>ad20c9d4-1309-4337-857d-dfecf5475c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;notifications-panel-wrapper&quot;]/div[@class=&quot;enter-notification notification-popup-wrapper&quot;]/div[@class=&quot;notification-popup-panel notification-popup-success&quot;]/div[1]/span[@class=&quot;block notification-popup-message&quot;]/span[1]</value>
      <webElementGuid>88579866-9863-40e8-ada4-9b524a3fd8e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div/div/div/span[2]/span</value>
      <webElementGuid>0203fe37-dde4-459b-899b-c46e19b0f5ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::span[3]</value>
      <webElementGuid>78936d09-b7ca-4a8f-9358-6866c06cdd87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Job'])[1]/following::span[3]</value>
      <webElementGuid>40bf1060-87c9-4027-b2e8-675bb3a51c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/span[2]/span</value>
      <webElementGuid>f1d6d583-87b0-4f47-b692-46d373b5cd51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
