<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_HiddenFiles</name>
   <tag></tag>
   <elementGuidId>39fd0177-caec-42b9-a306-3c6122911c10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'cb_show_hidden_file']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2d12fb3-21ec-4258-9b38-0c3788788537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cb_show_hidden_file</value>
      <webElementGuid>260bf9cb-199d-4d38-8954-263eddcf8a8d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
