<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Confirm_button</name>
   <tag></tag>
   <elementGuidId>22dfcca7-e90e-4d14-bdf7-b451a7258508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='confirm_modal_ok_btn']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'confirm_modal_ok_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>674bc1a2-d8f1-41a0-9b6c-75451d05b400</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm_modal_ok_btn</value>
      <webElementGuid>d2bb013b-434a-4da6-9ab0-2e24202d287b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
