<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Profiletab</name>
   <tag></tag>
   <elementGuidId>f75e1a6c-76b0-4075-94c1-5969e6e7e258</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'app_user_menu']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(@class,'avatar')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bf5a2693-84d0-4650-abbf-c02c1118914d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>app_user_menu</value>
      <webElementGuid>bd8f9213-d33d-4a0f-bc37-65e5e7312762</webElementGuid>
   </webElementProperties>
</WebElementEntity>
