<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>unityuser</name>
   <tag></tag>
   <elementGuidId>b0c4c22f-fe28-4511-8db7-c1567ef1ea36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@class, 'unity_user')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5fde90ff-592f-4859-bc00-e4917682eb05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unity_user</value>
      <webElementGuid>f0351d75-9b08-49c2-ab90-ec65ce656915</webElementGuid>
   </webElementProperties>
</WebElementEntity>
