<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Canvas_FilesPage_TileView</name>
   <tag></tag>
   <elementGuidId>b48bca14-e6e6-4870-b92e-524321d43b71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'fileviewer_filelist_container']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2a5f79e2-a0b6-49d7-866b-fb4fd4b47c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fileviewer_filelist_container</value>
      <webElementGuid>cf851814-677b-4fef-806f-374829fe4f9b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
