<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GotoFoldericon</name>
   <tag></tag>
   <elementGuidId>95664213-d02b-4e1a-8f72-098671c6c974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id = 'go-to-folder-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4aa4a28f-ad10-413b-926a-f785a8ed85aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>go-to-folder-icon</value>
      <webElementGuid>8c0e60c7-f5c4-4222-8813-4cde5b07c924</webElementGuid>
   </webElementProperties>
</WebElementEntity>
