<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ListItem_File</name>
   <tag></tag>
   <elementGuidId>2fd74ef1-17fd-41fa-9a75-6917ec5f9a8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id = 'upload_file_menu_item focus_enable_class']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='new_file_menu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>a0e31ea3-dfd5-453c-a5ab-eb274c8f3094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>upload_file_menu_item focus_enable_class</value>
      <webElementGuid>bd625842-a77a-4210-814c-9e62910c3dcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='new_file_menu']</value>
      <webElementGuid>67a0696d-abf2-4ce3-b2f9-d2f5dbdedd48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='new_file_menu_item focus_enable_class']/a</value>
      <webElementGuid>318e0b58-3d4f-48d1-bc47-46240d3a00ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Folder'])[1]/following::a[1]</value>
      <webElementGuid>5bcf8f65-1fa1-4c1d-a5b9-2835d5b0da33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Paste'])[1]/preceding::a[1]</value>
      <webElementGuid>bcccceb0-7d76-4c15-a246-78b8557251a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/ul/li[2]/a</value>
      <webElementGuid>131c3a77-d487-4d83-b9eb-3211800e8a77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
