<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ManageBookmark_title_link</name>
   <tag></tag>
   <elementGuidId>d3f93722-f7e9-49af-abf2-fdf4599cbc3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@title = 'demo1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7202a536-1f5d-46b7-834f-ae1c71aa8384</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>demo1</value>
      <webElementGuid>b517ac2f-3721-4120-afe3-34a7bc368344</webElementGuid>
   </webElementProperties>
</WebElementEntity>
