<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RowItem_CompressedFile_ListView</name>
   <tag></tag>
   <elementGuidId>48e1af78-6c3c-4390-baa6-0b1b7a5a8ca7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//label[(contains(text(), 'Compress_LV_archive_') or contains(., 'Compress_LV_archive_'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>acdba4ea-a08c-47d8-aa96-a9cd5167c719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compress_LV_archive_</value>
      <webElementGuid>da43b8b2-c9ce-4b7c-9a7d-4a5367b17ca9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
