<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_MoveToQueue</name>
   <tag></tag>
   <elementGuidId>c50ebad6-76c6-4ebb-a8e0-ec63001d0cae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'job_detail_movetoqueue_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ead793b5-5da9-4ee3-b48e-7e9df6520612</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_detail_movetoqueue_btn</value>
      <webElementGuid>84403101-4701-4f8c-8241-d03aa495764c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
