<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DropDown_accessQueue</name>
   <tag></tag>
   <elementGuidId>e9439664-8340-455c-9b1c-2118b15ace0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id = 'queue_accessQueue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>c48a61b2-5709-4cbe-b87a-efe4dd24a34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>queue_accessQueue</value>
      <webElementGuid>18b95c5f-af42-413f-a9b8-32e9e8c3b7ac</webElementGuid>
   </webElementProperties>
</WebElementEntity>
