<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Empty_msg_RunningFolder</name>
   <tag></tag>
   <elementGuidId>d7d446a0-91f8-483f-ad6c-4a1464f5e8a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'running-empty-message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f70806a8-1d4f-4e28-8a8c-79146ffed5a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>running-empty-message</value>
      <webElementGuid>1fa17e18-6a66-4ee8-894c-287a538f1e38</webElementGuid>
   </webElementProperties>
</WebElementEntity>
