<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_EditFile</name>
   <tag></tag>
   <elementGuidId>4b42dcc1-6eba-4e3c-971c-c6dc153d5b4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@data-automation-id = 'Edit']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4030428b-d6c5-4511-8c6f-430dfc8928f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>eeafb642-96b7-47b8-98ef-3ba80b8bc1c4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
