<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_CustomActionOutput</name>
   <tag></tag>
   <elementGuidId>4a88e147-db53-4e0d-8f1f-201280cd243d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'stdout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>aaffa5f8-af57-4ce9-847f-d5328e7f535b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>stdout</value>
      <webElementGuid>1bb0261f-bf9f-4cc0-a56d-fea0a55670d7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
