<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Upload_File_ContextMenu</name>
   <tag></tag>
   <elementGuidId>984acaa8-e48b-4bbe-a9b3-4f3eab8cfdb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'file_upload_element_running_job_upload']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e4f681a-3e78-43bd-8b23-1c7467514d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file_upload_element_running_job_upload</value>
      <webElementGuid>c3ee6c10-cec7-4a59-90e3-c3cf26815b73</webElementGuid>
   </webElementProperties>
</WebElementEntity>
