<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>File_InputFile</name>
   <tag></tag>
   <elementGuidId>27db57d2-7c74-4195-8841-68f92b1941e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-automation-id = 'bar.fem']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[equals(text(),'bar.fem')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8df950df-4d41-47ff-b9ea-52662f49c7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>bar.fem</value>
      <webElementGuid>a0535533-5cfa-4106-8e21-bb10a9a84505</webElementGuid>
   </webElementProperties>
</WebElementEntity>
