<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_DeleteIcon_Fileop</name>
   <tag></tag>
   <elementGuidId>10b213d3-2301-4016-a653-551aba2a14f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id = 'delete_icon']</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b10f1b74-e062-4f9d-91e9-8eb52999493d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delete_icon</value>
      <webElementGuid>c635c9fc-87b8-4d3f-a8f5-b0970c0248c0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
