<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TrialTestObject</name>
   <tag></tag>
   <elementGuidId>c92546b3-c0d3-4362-9aa6-0e234d4b62a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'job-file-inline-overlay']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>67eae145-dfc5-41a4-b807-17ac9bb10d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job-file-inline-overlay</value>
      <webElementGuid>b7d011e7-9231-4691-8072-0f2aa566333b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
