<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Monitor_Drop_down</name>
   <tag></tag>
   <elementGuidId>96a1788a-8860-4591-b39d-1bf9e699c414</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[contains(@class, 'rw-popup-container')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3bd7e9f5-9df1-4bee-a2fc-91d47e8b279a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rw-popup-container</value>
      <webElementGuid>f26b0d93-8e03-4c14-ae4f-6c38e710e981</webElementGuid>
   </webElementProperties>
</WebElementEntity>
