<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FileOwner_Text_Details</name>
   <tag></tag>
   <elementGuidId>15219926-8c32-4bf9-b534-3a11b4954122</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[(contains(text(), 'rohini') or contains(., 'rohini'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>5009c98e-575a-432e-beb0-bb963f8ccbce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>rohini</value>
      <webElementGuid>11ad1849-4927-4984-9898-6e552e4ebb9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;tabs&quot;]/div[@class=&quot;tabs__content&quot;]/div[@class=&quot;filecontent-fileviewer-container&quot;]/div[@class=&quot;filecontent-fileviewer-wrapper&quot;]/div[@class=&quot;SplitPane splitpane  vertical&quot;]/div[@class=&quot;Pane vertical Pane2&quot;]/div[@class=&quot;filecontent-fileviewer-container-wrapper&quot;]/div[@class=&quot;filecontent-fileviewer-container-right&quot;]/div[@class=&quot;file-content-viewer-wrapper&quot;]/div[@class=&quot;file-content-viewer-content-wrapper&quot;]/div[@class=&quot;file-content-viewer-file-details&quot;]/div[2]/ul[@class=&quot;file_Details_list&quot;]/li[2]</value>
      <webElementGuid>53395ecf-43fe-49bc-b319-89f734fb1fed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div[2]/div/div[2]/div/div[2]/div/div[3]/div[2]/div[2]/ul/li[2]</value>
      <webElementGuid>0fe79335-83ce-45c7-a3a8-d8760c58f708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Myfile.txt'])[3]/following::li[2]</value>
      <webElementGuid>b71cf8b2-9add-454e-ba3b-dbc9844f2ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uploading 0 items'])[1]/preceding::li[2]</value>
      <webElementGuid>58003e5e-bd36-41ce-97a3-572f32879812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='File Owner:']/parent::*</value>
      <webElementGuid>ca3ac51c-83dd-4370-9f44-2b6df1737ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[2]/ul/li[2]</value>
      <webElementGuid>718966df-1bf5-4a00-ab7e-4a686cb6d9c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
