<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pagination_number_status</name>
   <tag></tag>
   <elementGuidId>b8469ac9-3a05-420f-9e6e-17cb2f993fc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'pagination-number-status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ba743d49-0a1e-4f98-9088-68abfee4cc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pagination-number-status</value>
      <webElementGuid>40229ed9-69b6-4dea-b419-cb1a24b99b99</webElementGuid>
   </webElementProperties>
</WebElementEntity>
