<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TitleLink_Files</name>
   <tag></tag>
   <elementGuidId>9223800e-fea9-48f5-ab04-0976d37592c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[@id = 'app_files_tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>dc6f2ea9-bfd5-4b95-b5a6-c630e96d71de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> focus_enable_class</value>
      <webElementGuid>d5c30f1b-a5e1-4d81-bcf9-adcd087367eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Files</value>
      <webElementGuid>917655d8-fe68-4ad4-94d4-12997adf2adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app_files_tab&quot;)/a[@class=&quot;focus_enable_class&quot;]</value>
      <webElementGuid>11ac146c-e140-4673-9773-31bc2d728e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>app_files_tab</value>
      <webElementGuid>6e2b19cd-5154-4afc-a9a6-04dd251bd918</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='app_files_tab']/a</value>
      <webElementGuid>77c83396-688b-4f63-a06d-9bb692c5baed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Files')]</value>
      <webElementGuid>82b1c5f1-561e-4942-b10c-c54aaeec327a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::a[1]</value>
      <webElementGuid>7451f642-31f5-47a3-944a-7299df2766ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='There is no notifications to show at this moment'])[1]/following::a[1]</value>
      <webElementGuid>ebbf80a6-8206-40b5-8219-31364ccef42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jobs'])[1]/preceding::a[1]</value>
      <webElementGuid>6c81d4ce-173d-4121-b149-ff1d549c1136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sessions'])[1]/preceding::a[2]</value>
      <webElementGuid>87d43b80-dd32-41e0-b232-3dac5a39f68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>65991115-35f5-44f8-b51a-a613a753d621</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
