<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Queue_All_Filter</name>
   <tag></tag>
   <elementGuidId>f38c8244-f061-48a4-b405-79e49c35ead4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'cb_all-select-queueName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5a4c3e8-9a9a-4591-ab10-9df3a7ef20b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cb_all-select-queueName</value>
      <webElementGuid>39bc08c4-254a-4517-8c8c-027a9540b7b0</webElementGuid>
   </webElementProperties>
</WebElementEntity>
