<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Server_All_Filter</name>
   <tag></tag>
   <elementGuidId>6d500a2e-a4e4-4df4-a3fd-4f647e25579d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'cb_all-select-pbsserver_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29a33a5e-e12a-47c1-9f6b-d3da1adcfb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cb_all-select-pbsserver_id</value>
      <webElementGuid>1e3f48bc-1178-4022-85d0-08879557b08f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
