<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Status_Filter_All_checkbox</name>
   <tag></tag>
   <elementGuidId>2a762020-1053-4180-ba29-c3b5a61fd792</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'cb_all-select-jobState']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59b8da1c-9086-4675-a935-ca96663da2de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cb_all-select-jobState</value>
      <webElementGuid>97f599a6-c39b-457d-9e08-77812c123855</webElementGuid>
   </webElementProperties>
</WebElementEntity>
