<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Submit_jobusing_appdefs</name>
   <tag></tag>
   <elementGuidId>61d3bcab-e0c1-4bed-ad27-5854d3f3b5f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'job-monitor-application-tile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bd393184-3570-41d2-8cae-06ec4bf32d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>job-monitor-application-tile</value>
      <webElementGuid>1bab80d4-57e3-4aa8-8432-502043b91c11</webElementGuid>
   </webElementProperties>
</WebElementEntity>
