<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AppList_ShellScript</name>
   <tag></tag>
   <elementGuidId>e2c829ce-a4ae-4c78-8a9a-20971707dcbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'ShellScript']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ShellScript']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ShellScript</value>
      <webElementGuid>973b812c-fe48-4335-9310-fa85d0d8daa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ShellScript</value>
      <webElementGuid>50a3e5cc-c9fd-4d1c-83b3-36be2080ab50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ShellScript&quot;)/div[@class=&quot;application-tile-content&quot;]/div[@class=&quot;application-tile-info&quot;]/span[@class=&quot;show-text-ellipsis&quot;]</value>
      <webElementGuid>1d43a552-5778-4fa2-b1a1-82f1d41c8c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ShellScript</value>
      <webElementGuid>15a8e95d-ae5c-42c5-905d-32770bb19119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0da02090-3a4b-4af1-9f65-83d25435b39c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ShellScript']/div/div[2]/span</value>
      <webElementGuid>fe953ee9-b5d9-4b58-a44c-abe67b03ffdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch'])[3]/following::span[1]</value>
      <webElementGuid>bc902e22-8587-4ed6-a852-fd0c798ccaaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RADIOSS-SMP'])[1]/following::span[2]</value>
      <webElementGuid>4585abc2-d344-4ea8-8014-6217e905498d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batch'])[4]/preceding::span[1]</value>
      <webElementGuid>393abd47-1e6b-4a09-80a1-8d0eecf2cb7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/preceding::span[2]</value>
      <webElementGuid>238d4f22-ea9a-4618-95f0-ec8650f4554c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/span</value>
      <webElementGuid>9f59dfc5-241f-4d35-9261-787379d3d9e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
