<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Save Profile</name>
   <tag></tag>
   <elementGuidId>f5172979-1611-4490-b1d0-182c07ff9585</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@id = 'save_profile_dlg_title' and (text() = 'Save Profile' or . = 'Save Profile')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='save_profile_dlg_title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>546efd83-bfc3-4559-a7d7-1a11943ef219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save_profile_dlg_title</value>
      <webElementGuid>4ce804a0-e2fa-4a1f-a617-a61f0f0a5b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>generic-header</value>
      <webElementGuid>1b8053a1-23cf-42ec-8d93-1ea2870eaaff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save Profile</value>
      <webElementGuid>8b05018b-217f-40c9-bdeb-f59b1da69a78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save_profile_dlg_title&quot;)</value>
      <webElementGuid>e7172312-5aad-4112-8e9b-668d10fadc84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='save_profile_dlg_title']</value>
      <webElementGuid>2696c252-bc9f-4b22-97f0-972aa360f887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='save-profile-dlg']/div/div/form/div/label</value>
      <webElementGuid>7848cb27-5c54-47d7-8a23-910fb0cec21b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'save_profile_dlg_title', '&quot;', ')')])[1]/following::label[1]</value>
      <webElementGuid>648725d3-3f13-4543-a8aa-798261d38c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::label[1]</value>
      <webElementGuid>94222f17-1b24-41c7-8a1c-a0bca6a011bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/preceding::label[2]</value>
      <webElementGuid>40d6ca1c-04f2-4fd6-b66c-0bf593a0cc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/form/div/label</value>
      <webElementGuid>61f44e84-33e4-4d03-8ae6-631371bc4577</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
