<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>accessmanagment_userslist</name>
   <tag></tag>
   <elementGuidId>c32045fd-dbc8-4992-a121-d823cbf11a25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[(contains(text(), 'rohini') or contains(., 'rohini'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e7ba2497-6203-4d3a-a2e4-7c8ef862b48a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>rohini</value>
      <webElementGuid>a60a3cc5-f2ed-4247-b05e-e81b330c6953</webElementGuid>
   </webElementProperties>
</WebElementEntity>
