<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Apply_button</name>
   <tag></tag>
   <elementGuidId>ba8aa9bf-eef5-443a-8e79-67f770ad2837</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'sendacopy-modal-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>172996c1-ab1a-4083-8103-9b4f2c923ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>sendacopy-modal-btn</value>
      <webElementGuid>f21dff5e-e6df-4f1a-b2cd-bac4db165ba8</webElementGuid>
   </webElementProperties>
</WebElementEntity>
