<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_users</name>
   <tag></tag>
   <elementGuidId>cb23d48a-8eaa-4e66-b082-7084304ead3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = 'users-list' and (contains(text(), 'pbsadmin') or contains(., 'pbsadmin'))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class = 'users-list']/div/div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1474759f-c7ab-488c-a862-9851fb8b7713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>users-list</value>
      <webElementGuid>9bdb494d-4dd0-4db1-9403-e2e01c97b9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pbsadmin</value>
      <webElementGuid>7c2fffe8-1a4b-4e3c-8952-2c2eb7a0b10c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
