<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FileName_Text_Details</name>
   <tag></tag>
   <elementGuidId>b988d8a6-b744-4042-8ec3-737e09ca0f54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'Myfile.txt' or . = 'Myfile.txt')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>99c74d17-7c77-47c0-9bf1-c3010509bce9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Myfile.txt</value>
      <webElementGuid>035f68c8-7d2e-4edc-ba2f-31354bb210e6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
