<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Word_wrap</name>
   <tag></tag>
   <elementGuidId>ff6c205b-f952-4b73-8f16-f08da13c7b1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//label[@id = 'wordwrap']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>242db14f-6379-4525-839d-d34a3b9575bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wordwrap</value>
      <webElementGuid>c843f53e-9850-42d9-9510-c30853bf5083</webElementGuid>
   </webElementProperties>
</WebElementEntity>
