<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AppName</name>
   <tag></tag>
   <elementGuidId>89ef64a7-16a5-4756-9091-8f0330da6f93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='app_name_input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#app_name_input</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'app_name_input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>adee9695-2ba9-4737-93c8-f0ae35240643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>app-name-input</value>
      <webElementGuid>92aa7aa5-fb85-458c-8b57-841ccb807fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>app_name_input</value>
      <webElementGuid>0f2c7d6a-e985-4265-be10-4b330f5aa9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bf31573f-721f-4840-82bd-b14d1486218e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>appName</value>
      <webElementGuid>4e56d1fe-e3af-4683-a87f-da51c1dcedae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Untitled</value>
      <webElementGuid>791af635-aca5-4206-a8eb-78862f1119b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app_name_input&quot;)</value>
      <webElementGuid>398f09aa-0fa4-4fca-ac5b-dc333765036d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='app_name_input']</value>
      <webElementGuid>66d7673b-411b-41cd-8e86-a117bffb5acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>efc61a48-8ebb-44b5-8926-cf169b556eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>7422f203-9229-4450-9016-41566688cb09</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
