<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Editapp</name>
   <tag></tag>
   <elementGuidId>6df3d855-4f29-4a4f-a992-ca9bd0b25a78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-automation-id = 'Editapp']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@title='Editapp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c9e86207-4fcf-4296-ac02-b461bbd15532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>Editapp</value>
      <webElementGuid>8363d4e7-98d4-4b41-8568-a0c293a38578</webElementGuid>
   </webElementProperties>
</WebElementEntity>
