<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Newapp</name>
   <tag></tag>
   <elementGuidId>1653beb1-422e-4aa8-b0c8-cff373b3be3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-automation-id = 'Newapp']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Newapp')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7ac3616a-364d-48f6-a9ee-946099455d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>Newapp</value>
      <webElementGuid>0f14a639-40d2-49de-9323-4bcfa63fed42</webElementGuid>
   </webElementProperties>
</WebElementEntity>
