<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Newapp_clone</name>
   <tag></tag>
   <elementGuidId>414a74e4-5cf6-4809-a5ae-145d3b64adb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-automation-id = 'Newapp_1']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Newapp_1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bbcea26a-4119-491a-91ef-3af56dca6bd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>Newapp_1</value>
      <webElementGuid>190cb7ef-47ad-47b9-864e-b3e610f855ef</webElementGuid>
   </webElementProperties>
</WebElementEntity>
