<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TestJm_left</name>
   <tag></tag>
   <elementGuidId>8277b026-d810-494a-922b-b1a9e814bbdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-automation-id = 'TestJM']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'TestJm')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a13e6bd2-d2d4-47fb-bef4-cfe60cd4782a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>TestJM</value>
      <webElementGuid>fdf900f2-ddb5-46d9-8c61-6006e0573b8e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
