<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Testapp_clone</name>
   <tag></tag>
   <elementGuidId>9e450758-b646-4284-8471-52247e327def</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-automation-id='Test12File']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Test12File_1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>35f084be-c290-4d06-9132-d21200dae796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>Test12File'</value>
      <webElementGuid>f4e987a2-500d-4e41-924c-da02a8b11be7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@data-automation-id='Test12File']</value>
      <webElementGuid>3f37e7ea-7297-4301-9f47-d053f9ca7bca</webElementGuid>
   </webElementProperties>
</WebElementEntity>
