<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tooltip_Inputfile</name>
   <tag></tag>
   <elementGuidId>67c8c4d1-b90b-433a-a69f-1db5e971df0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'toolTipForPRIMARY_FILE']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='root']/div[1]/div[3]/div[1]/div[1]/div[3]/div[1]/section[1]/div[2]/form[1]/div[6]/div[3]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e82b3e68-4ed1-4807-a1e7-1a0c34832b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>toolTipForPRIMARY_FILE</value>
      <webElementGuid>533fde6d-505c-4148-8eb7-e1ace0f2932a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
