<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Untitled_app</name>
   <tag></tag>
   <elementGuidId>67a50dc9-93ff-4c94-94b5-1e257f1e1ad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-automation-id = 'Untitled']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Untitled')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6acc76b2-d583-42b8-b222-674ab6d95031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>Untitled</value>
      <webElementGuid>de05f6c2-5571-4c3e-b73c-926b940479fc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
