<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Withoutpublish</name>
   <tag></tag>
   <elementGuidId>4f2395d4-3936-44d4-b723-6e880a09cd96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@data-automation-id = 'Withoutpublish']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Withoutpublish')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a9fd227-d67a-4b29-8ef6-34d8a21240b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>Withoutpublish</value>
      <webElementGuid>8afafdec-c93b-470b-8c27-08f46bab90ae</webElementGuid>
   </webElementProperties>
</WebElementEntity>
