<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>GenericTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c0b3d89d-ec76-43b1-b9a6-1bce73d8cdc7</testSuiteGuid>
   <testCaseLink>
      <guid>be419209-23d1-4b1d-947b-6d57438eda93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WindowTitle/GetWindowTitle</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7e16d2e-0b13-4e73-957e-8575c0bc254e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66aa9127-13ad-43ab-a072-53eea7e467e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e26fe06-f737-4bad-8a94-3ce18a62cbb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32ed20d1-8dca-4e69-8531-241f053a6b06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3080d45e-d09d-41dd-9260-5c6b4f00d2ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>826205c1-167c-46ec-9ce3-1cdfc16899ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98fa2418-ff60-4297-8a4f-c8ccc94897e5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2fdb77a-527c-4749-9cd1-216ea26f248d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WindowTitle/JobApplicationFilterVerification</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b292f73-6e4e-44a1-afc8-5515f4bae6f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89e76b7e-4494-4c6e-ba5e-4dc4c0ebf02e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af74ead0-ad1a-48e1-9136-865ab3d1a631</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f81dc48-02c2-4203-b874-992fce0dd013</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c489a08a-3892-493a-8e02-60b66e3abd97</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobMonitoring/Jobdetailspage_summarypage-Layout-Verifications</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>309c0496-7340-4e08-ac3e-a5523038cd93</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>2-2</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestData2020.4</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>309c0496-7340-4e08-ac3e-a5523038cd93</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>jobState</value>
         <variableId>f9ddff65-dbdd-43df-9732-32237ac18f55</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>309c0496-7340-4e08-ac3e-a5523038cd93</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>60839071-ac4c-4419-b918-d5dc0ab90412</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>309c0496-7340-4e08-ac3e-a5523038cd93</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>25cf6dfc-64f4-471a-9221-c1ddbf78b044</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>31e07c52-18d4-4bbc-ab7c-74f51dc57d58</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WindowTitle/JobColumnVerification</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd27047a-f290-4db7-a132-87197302a1fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c562e8d8-b57e-447b-a968-93b5d778e6ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>69c07e6c-ab8b-4590-9680-a4b370aab2f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2019.3/AltairAccesslogo_JobsTab</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>015be0ef-4498-4dcd-9c0f-8644f8b7aebe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee1669e4-484d-446c-a6cd-6805d5cfa8fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9fa49202-fee8-4fed-9fdb-0c148898ec2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/2019.3/ProcessWith_Optistruct</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecebbc7d-c682-48a7-ae90-b89b965c63d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee159a2f-337e-4f8f-84d6-4c5206a6e4f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13bb1d38-b7f1-4761-8678-46a35eed5c08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8837c03c-6bb4-4f29-b5bd-45ea002c0ebb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/2019.3/RunningFolder_UploadFile</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04eb5cd4-5982-4990-9331-4a7cd5c4086a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b45b6c8c-8a07-4e38-8fd1-685dffd2e8f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2495b9a2-4866-425f-b5d0-edc81a39402a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3f09da6b-bf75-44f5-9ec3-95e986e80736</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FilesModule/FileViewer2020.4</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1bf37a3e-de3d-471a-955a-a4a5411c6967</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1-3</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataFileViewer2020.4</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>1bf37a3e-de3d-471a-955a-a4a5411c6967</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>fileName</value>
         <variableId>022826e7-4f7e-4c27-8f7c-da4fa281a867</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1bf37a3e-de3d-471a-955a-a4a5411c6967</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>160b0f6c-199d-4e5c-8d08-4e99a9018074</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1bf37a3e-de3d-471a-955a-a4a5411c6967</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>a5a51141-ab78-4328-838e-a0c015f8caf1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cfe9d65c-2264-4e14-9adc-f468a556ae61</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FileProcessWith-2020.4</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4ed67c93-e780-4950-9ecd-1ac4691aa408</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1-4</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataFileViewer2020.4</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f437cb72-d460-45b9-8457-506e053653fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>41e4999d-53fd-4ac2-ac7d-b32dd14c947d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23a39b4b-3cb1-49da-b642-9ada0fa81727</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a90f198e-6076-4a17-8e68-6f8a2df56aff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>061b16b1-00b0-4549-9442-8ba2fd0e9bdf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>717d5e86-3349-4836-8c36-9a645d19d409</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a06a0491-5102-480b-a4ea-2a2aa193d23e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e44c0250-17a1-4209-bc0d-4395bbd2f8df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobMonitoring/Jobdetailspage_FileViewer-2020.4</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbe2372f-42c1-49a2-814d-03b4a4ed1b1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d214cfc-ed7a-438b-b9ca-7ad4eec8412e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd7761bd-5371-43eb-9269-070cb08d8352</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0e49dd6-643d-456c-b3b1-b287bf80341b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13d39499-a670-42b5-8659-8d3090f96932</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
