<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>JMFilters</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>65909afd-a262-4284-95d9-97ccce2ad382</testSuiteGuid>
   <testCaseLink>
      <guid>49406418-af2a-497b-a48d-169784a58f96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Upload/AD-2855-Column Sorting</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00b7731d-b760-4882-878e-da6d96662b41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aabfaf6d-51fd-4061-9821-85df17cf22ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f68b7d4-a899-4d69-9a4a-b349b5d1e2dc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8ec914af-c956-4c56-b59d-628b08719024</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobMonitoring/JobFilters-SaveFilters</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1ecd16e6-f554-4e36-9aec-221ca4cfdf1f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>4-10</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataJobFiltersSave</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>1ecd16e6-f554-4e36-9aec-221ca4cfdf1f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>cb8b7af0-b33a-4579-bb88-cb75a300f49f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1ecd16e6-f554-4e36-9aec-221ca4cfdf1f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FilterCategory</value>
         <variableId>b6437064-d5b7-4b74-b7bf-f2b2707f54df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1ecd16e6-f554-4e36-9aec-221ca4cfdf1f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FilterValue</value>
         <variableId>68835494-617e-4570-b656-d448266da96d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1ecd16e6-f554-4e36-9aec-221ca4cfdf1f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FilterTitle</value>
         <variableId>bf9c44e2-408c-4f9f-8870-f7f68adfce91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1ecd16e6-f554-4e36-9aec-221ca4cfdf1f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dataAttribute</value>
         <variableId>48734636-1105-4bfe-bf68-14111bfc8441</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1ecd16e6-f554-4e36-9aec-221ca4cfdf1f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>AllJobsUser</value>
         <variableId>784c0350-028b-4992-8787-35beba88226b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>1ecd16e6-f554-4e36-9aec-221ca4cfdf1f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FilterName</value>
         <variableId>7aa31cb2-ccae-42a2-abe1-247e8e2d98bb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bd287dd7-b0de-4004-b518-fedaa52b09e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobMonitoring/JobFilters</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cbfd5f43-85fb-4643-82b4-2d15b16692fb</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>11</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataJobFilters</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>cbfd5f43-85fb-4643-82b4-2d15b16692fb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>ace71100-db45-4bac-9cf7-4e06beb3fcfb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cbfd5f43-85fb-4643-82b4-2d15b16692fb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FilterCategory</value>
         <variableId>da517e3c-6f16-45ad-a631-1f8d0f1e7ad4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cbfd5f43-85fb-4643-82b4-2d15b16692fb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FilterValue</value>
         <variableId>85fe5725-d3b0-47ef-8404-aebd0ef7e59e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cbfd5f43-85fb-4643-82b4-2d15b16692fb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FilterTitle</value>
         <variableId>6cb8d038-a65f-4a85-95f4-15ca8ef3b50e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cbfd5f43-85fb-4643-82b4-2d15b16692fb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dataAttribute</value>
         <variableId>add707ea-162f-4718-9997-8cb889c18040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>54bc3327-1895-48a0-ab95-3335411c3aba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40d68681-c5af-4b2f-ac13-e9fc22540cb7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>baf856e0-9c51-4b27-b4c1-89c00b09cf64</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobMonitoring/JobFilters-SaveFilters-DeleteFilter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab72b31e-8363-44da-a321-301ff1535bf2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e683da7f-b440-4ffd-9ab3-e4d0221098ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>488bdad1-b25f-4332-aa67-b5f1516d3fe5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9633f5cd-4e51-4d25-afeb-0623d3a4c0b8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e08466a3-c8c6-461b-b6ba-9ae8717a20e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a52efbd1-1f37-4e3b-884b-5d246331e84e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d7a8e47-aa07-4eb1-b1c6-904487ae7a2a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>62088acb-d161-498a-8e9c-4b783393c5f4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobMonitoring/JobSeacrh</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afeb7723-7576-4e85-ae6f-ba63281eb589</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf79c37b-4483-4f58-a5c9-c7a7c7d69ade</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d788f12-5808-4ac4-9b57-fe14d66bdc2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d99dbbb6-3b44-4baf-b6f8-2bbfabfdc987</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d65828a-64dd-4d09-8922-07787f77c67f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobMonitoring/JobDetailsPage_LayOutVerifications</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>15edd67c-c0dc-4e38-88b2-0134b4014119</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>1</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobMonitoringGenericOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>15edd67c-c0dc-4e38-88b2-0134b4014119</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>JobState</value>
         <variableId>b95a9fac-0595-4142-958e-7ec79e23ea6c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>15edd67c-c0dc-4e38-88b2-0134b4014119</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>e355021e-cb77-4652-bf65-137a4779e533</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>15edd67c-c0dc-4e38-88b2-0134b4014119</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>ee8f4c65-18f4-4728-905c-411aacdb30ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81e3c659-3cfd-4666-949c-0615bedacd15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobMonitoring/JobsTable-AddCols</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>83f9b37a-0b3d-4bb9-a947-fdbac6bf3f07</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>20-24</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForAddingColJobtable</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>83f9b37a-0b3d-4bb9-a947-fdbac6bf3f07</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ColCheckBx</value>
         <variableId>906d93d7-9edf-49da-91fb-d3eb163252e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>83f9b37a-0b3d-4bb9-a947-fdbac6bf3f07</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ColLable</value>
         <variableId>3696c598-c23c-4fb6-acad-afcb3fbca84d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>83f9b37a-0b3d-4bb9-a947-fdbac6bf3f07</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>fb7b17c6-f07a-44db-95a6-014c8974af45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>83f9b37a-0b3d-4bb9-a947-fdbac6bf3f07</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ColName</value>
         <variableId>6167355e-2e2d-4222-a224-47237304a662</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>83f9b37a-0b3d-4bb9-a947-fdbac6bf3f07</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>e89d0e5c-b39d-46a1-a7bd-3e35a02dde8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>83f9b37a-0b3d-4bb9-a947-fdbac6bf3f07</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>dataAttribute</value>
         <variableId>1e13a056-4455-4e2b-bc18-2e205a4fa439</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5eeea36b-2d3f-4c63-a5a8-258434f0fb54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Upload/AD-3418-Verify Applications Filter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5885325f-4b82-46f0-9fe0-68b0d1220aeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf35b091-997d-4756-b7bb-5d3c04461d9a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f429f4f-b195-46ee-af68-b7c223980863</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Upload/Default_Filters</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9ba3808-8b00-4693-ac33-8940ba7d6c26</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aad3736f-8715-4ffb-b6d9-46c228c2a90d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Upload/Custom_actions</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36613ca7-02ff-44ad-a63a-66d42a1fca50</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edbdda98-3662-45dc-9cca-c374182f15b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef6339f6-917f-4be7-9bdb-017822e4c737</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a3b02cf-ddca-4691-9b82-5a4875a89cb4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobMonitoring/JobFilters-SaveFilters-MaxCount</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fe97f86-abc2-4212-92cd-9dba59c37e44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e85ec3a7-aa32-45f1-9349-99cee8d1a041</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d56b7ca3-04cf-4d28-bd31-098ee71abbcc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2ff0dd6-55d2-4806-a97c-f47e8385d0eb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4825c27-e583-4def-8018-dfd922551744</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>266c33c0-f3d2-4b8e-8eae-571715039ba7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02b4f6a9-2244-4eaa-895d-cab9c1667543</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
