<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>paginationlistitems</name>
   <tag></tag>
   <elementGuidId>2e816a69-3e5a-41d8-a934-41734eac3583</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[(contains(text(), '100') or contains(., '100'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>04ddd528-db1e-461f-a539-267d6a33ec65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>7a4dfd39-0ecf-481a-be0c-3749a78b26ce</webElementGuid>
   </webElementProperties>
</WebElementEntity>
