<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pagination_dropdown_listbox</name>
   <tag></tag>
   <elementGuidId>9dba5185-1f58-4690-aaa5-a36af9268104</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'pagination-dropdown-files_listbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37a387f7-45b8-45a7-b276-5f9060e9547c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pagination-dropdown-files_listbox</value>
      <webElementGuid>0bd1df57-9f2f-4813-a03c-5e288dd55ed7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
